src/components/Navbar.js
Previous PR was accidentally merged with changes required and this is the follow up
=> Correction to the previous PR

tests/test.js
Fail the test if upload fails.
=> Fix false success in Paratext upload test.

tests/test.js
Fix intermittent errors in the following tests:
- should check empty chapter report
- should check incomplete verse report
- should check multiple space in verse report
=> Fix automated tests for reports.

src/components/ProjectList.js, src/components/ProjectListRow.js, src/components/Settings.js, src/helpers/giteaAdapter.js
=> Rename generic sync code to use generic identifiers

src/components/ProjectCreate.js, src/components/ProjectListRow.js, src/components/Settings.js, src/helpers/giteaAdapter.js, tests/test.js
- E2E test suite for WACS/Gitea sync.
- Minor testability tweaks.
- Minor error-handling improvement.
Resolves #37
=> E2E tests for WACS

src/components/TranslationPanel.js
Worked on  issue #38 and working on test cases..
Please review my PR
=> Issue#38 Cursor disapper onDouble click resolve

src/components/Navbar.js
Worked on #Issue67, tested and pushed for review.
=> < and > bug fixed

src/lib/full_bible_skel.json
Fix for translation statistic bug. Added missing verses in the skeleton
=> Added missing verses in skeleton

package-lock.json, src/components/Settings.js
Solved the issue by changing the expand more icon to the correct place in Import-Report (Successfully Imported Files) section.
=> Changed the expand-more icon to correct place

public/index.html, src/App.js, src/components/Navbar.js
Made changes for slowing down issue while opening translation help and break down while surfing (issue #66 )
=> translation help break while surfing issue

src/util/usfm_import.js
fix for issue #74 , tested and working
=> Added fix to ignore Non-USFM files in the reference directory 

src/util/usfm_to_json.js
=> Added fix for path issue

src/assets/stylesheets/style.css, src/components/Settings.js, src/translations/ar.js, src/translations/en.js, src/translations/es.js, src/translations/hi.js, src/translations/pt.js
Added folder ICON for importing the files from the folder and Enabled typing for direct import of a folder or file using the directory path. #78 made the changes and tested it.
=> Enabled typing to import the files and added ICON for folder selection

src/assets/stylesheets/style.css, src/translations/ar.js
Changed CSS that throws build error, made some minor changes and tested
=> Add build fix and css change

package-lock.json, package.json, src/components/Navbar.js, src/components/Settings.js, src/util/usfm_to_json.js
Code change for imported reference compare modes with working insertion and deletion counts for all languages #84
=> fix for compare and diff with all references

src/util/usfm_to_json.js
Solved #87  App break issue while importing invalid usfm files(wrongly tagged verses and chapters), Tested it.
=> Solved App break issue while importing invalid USFM files

src/components/Settings.js, src/util/usfm_import.js
code change for multi-selection of USFM files on reference import #86 . Please review my code
=> Multi select for refernce bible files

src/components/Navbar.js, src/components/Settings.js
Fix for reload after import #17  and tested, Please review my code
=> Import reload fix

src/components/Settings.js
Both the event function names where same for the "Sync" and "Import Report", cleared the issue by changing the name and added separate names for the functions, tested it.
=> Paratext expansion error solved

src/components/Settings.js
=> clean css changed for rtl ltr

src/components/TranslationPanel.js
=> Added copy-pasting element-fix

src/components/Settings.js
test and working with caps language code
=> Compare fix for caps langcode

public/electron.js
Enabled copy paste for mac on the menu bar and tested working
=> added shortcutkeys for mac

package.json
Changed Author and enabled electron builder. Not tested
=> added mac buid-fix and metadata change for mail in package.json

src/components/ReferencePanel.js, src/components/TranslationPanel.js
Solved the multiple paste issue and tested it.
=> added malfunction fix

package.json, src/components/ProjectListRow.js
Paratext sync got broken, worked on the issue and the sync is working and tested it.
=> Paratext sync is working

public/index.html, public/loader.css, src/components/Search.js
On repetitive find and replace functionality chapter gets duplicated and pushed copy to further chapter. Mostly happens for zero occurrences save. Fixed the issue and tested it.
=> Find and replace malfunction on zero occurrences save

src/components/Navbar.js, src/components/ReferencePanel.js, src/util/export_css.js, src/util/export_html.js, src/util/json_to_usfm.js, src/util/usfm_to_json.js
Added \m tag support, Tested it.
=> M tag with line break preserved on import

src/components/ProjectListRow.js
Fixed the issue by allowing to import content from **p** and **q** tags into their respective verse only. 
And while uploading back if the content has any unjoined verse(s) then in the paratext the last verse was getting deleted. Identified and fixed the issue.
Tested it.
=> Fixed the issue by allowing to import content from p and q tags

src/Audio/AudioApp.js, src/Audio/components/BottomBar/BottomBar.js, src/Audio/components/Loader/Loader.js, src/Audio/components/Loader/index.js, src/Audio/components/Loader/loader.css, src/Audio/components/RecorderNav/RecorderNav.js, src/Audio/components/RecorderNav/index.js, src/Audio/components/Visualization/AudioAnalyser.js, src/Audio/components/Visualization/AudioVisualiser.js, src/Audio/context/StoreContext.js, src/Audio/core/createPauseData.js, src/Audio/core/mergePause.js, src/Audio/index.js, src/assets/images/DiffFiles.svg, src/assets/stylesheets/style.css, src/components/AutographaStore.js, src/components/Footer.js, src/components/Navbar.js, src/components/TranslationPanel.js
Added code for joint verse support, complete chapters, and deletion verse, appending or pause, call each verse previously recorded time
=> Audio Version.2

src/Audio/components/RecorderNav/RecorderNav.js, src/Audio/context/StoreContext.js, src/components/TranslationPanel.js
Joint verse audio diable and complete chapter flag update and remove the complete flag on un-joinvese
=>  Joint verse complete support with audio

package.json, src/components/AutographaStore.js, src/components/FontSelect.js, src/components/TranslationPanel.js, src/translations/ar.js, src/translations/en.js, src/translations/es.js, src/translations/hi.js, src/translations/pt.js
Adding Font Change functionality for translation panel, this functionality fetches fonts from the system. added translations for UI.
Tested it.
=> adding font change functionality for translation panel

package-lock.json, package.json, src/App.js, src/components/AutographaStore.js, src/components/Footer.js, src/components/Menu.js, src/components/SubMenuItem.js, src/components/TranslationHelpsMenu.js
Code change for the integration of Translation help more gateway languages and CSS tweaks
=> Added more languages for translation help

package-lock.json, package.json, src/Audio/components/BottomBar/BottomBar.js, src/Audio/components/BottomBar/useTimer.js, src/Audio/components/RecorderNav/RecorderNav.js, src/Audio/context/StoreContext.js, src/Audio/core/mergeAudios.js, src/Audio/core/verseExport.js, src/components/Footer.js, src/components/Navbar.js, src/translations/ar.js, src/translations/en.js, src/translations/es.js, src/translations/hi.js, src/translations/pt.js
- Ability to verse export on to the specified user location
- Replacement of press and hold based recording functionalities with a normal button click
- Disabled Translation helps feature
=> Audio minor feature and UX update

.github/workflows/node.js.yml
- Removed deprecated auto `version` fetch for builds
=> Github actions update

package-lock.json, package.json, src/Audio/components/AudioPlayer/Player.js, src/Audio/context/StoreContext.js, src/Audio/core/mergeAudios.js, src/components/TranslationPanel.js
- Playback player changed `html5-player` to `react-player`
- Chapter export path change (to be inside the folder)
- version update to `0.2.1beta-1`
=> Playback bug fix with chapter export path change
